// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
 
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkNNlQ4UuuZQVlFMvl-Fyx5q1wFAZk94k',
    appId: '1:939233679214:web:d6d4d547e44a2e9414137f',
    messagingSenderId: '939233679214',
    projectId: 'connectcrm-5899e',
    authDomain: 'connectcrm-5899e.firebaseapp.com',
    storageBucket: 'connectcrm-5899e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-upwkNq7pI0K9pTbUAj6Hc0JPzCnsTw',
    appId: '1:939233679214:android:5e9f5632d883ed1d14137f',
    messagingSenderId: '939233679214',
    projectId: 'connectcrm-5899e',
    storageBucket: 'connectcrm-5899e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__PjLSgprl9M8H9vZY3w1Tl_-w8MfjzE',
    appId: '1:939233679214:ios:c4bdf502542de0df14137f',
    messagingSenderId: '939233679214',
    projectId: 'connectcrm-5899e',
    storageBucket: 'connectcrm-5899e.firebasestorage.app',
    iosBundleId: 'br.com.connectcrm.connectcrm',
  );
}
